version: '3.1'

services:

  database:
    image: postgres

    ports:
      - 5433:5432

    networks:
      - sls-network

    environment:
     POSTGRES_USER: root
     POSTGRES_PASSWORD: dev

    volumes:
      - dbdata:/var/lib/postgresql

  sls:
    build:
      context: .

    environment:
      spring.profiles.active: postgres
      server.port: 8080
      sls.db.hostname: database
      sls.db.username: root
      sls.db.password: dev
      sls.db.name: postgres
      sls.db.port: 5432
      sls.schema.name: public
      env.hocs.api.user: admin
      env.hocs.api.pass: admin
      env.hocs.api.host: https://vagrant.hocs.homeoffice.gov.uk:8080
      hostname: sls:8080

    depends_on:
      - database

    ports:
      - 9002:8080

    networks:
      - sls-network

    command: /app/scripts/run.sh

    volumes:
      - ../hocs-data/data/:/app/data/

networks:
  sls-network:

volumes:
  dbdata: {}